# Generated by Django 4.2.7 on 2023-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
