# Generated by Django 4.2.7 on 2023-11-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base',
            field=models.CharField(default='EUR', max_length=3),
        ),
    ]
